[package]
name = "perft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = { path = "../chess" }
clap = { version = "4.4.7", features = ["derive"] }
colored = "2.0.4"
rayon = "1.8.0"
