[workspace]
resolver = "2"
members = [ "simbelmyne", "chess", "uci", "tuner", "macros"]
default-members = ["simbelmyne"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
debug = 1
panic = "abort"
strip = false
