[workspace]
resolver = "2"
members = [ "simbelmyne", "chess", "uci" ]
default-members = ["simbelmyne"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
debug = 0
panic = "abort"
strip = true
