[workspace]
resolver = "2"
members = [ "crates/*" ]
default-members = ["crates/cli"]

[toolchain]
channel = "nightly"

[profile.dev]
opt-level = 3
codegen-units = 1
debug = 1
panic = "abort"
strip = false
overflow-checks = true
lto = "thin"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
debug = 0
panic = "abort"
strip = true

[profile.profiling]
inherits = "release"
debug = 1
strip = "none"
