[package]
name = "simbelmyne"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
chess = { path = "../chess" }
engine = { path = "../engine" }
colored = "2.0.4"
clap = { version = "4.4.7", features = ["derive"] }
