[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.70", features = ["extra-traits", "full", "visit"] }
uci = { path = "../uci", package = "simbelmyne-uci" }

[features]
default = []
spsa = []
