//! Find all the legal moves for a given board state
//!
//! Moves are generated by piece type, so we can shortcut, e.g. when only the
//! king is allowed to move.
//!
//! All the move generating functions are parametrized by a `QUIETS` const
//! generic that decides whether or not to include quiet moves.

use arrayvec::ArrayVec;
use itertools::Itertools;

use super::moves::BareMove;
use crate::attacks::between;
use crate::attacks::rays;
use crate::attacks::*;
use crate::bitboard::Bitboard;
use crate::board::Board;
use crate::movegen::castling::CastleType;
use crate::movegen::moves::Move;
use crate::piece::Color;
use crate::piece::PieceType;

pub const MAX_MOVES: usize = 218;

pub type MoveList = ArrayVec<Move, MAX_MOVES>;

pub trait GenType {
  const TACTICALS: bool;
  const QUIETS: bool;
}

pub struct All;
pub struct Tacticals;
pub struct Quiets;

impl GenType for All {
  const TACTICALS: bool = true;
  const QUIETS: bool = true;
}

impl GenType for Tacticals {
  const TACTICALS: bool = true;
  const QUIETS: bool = false;
}

impl GenType for Quiets {
  const TACTICALS: bool = false;
  const QUIETS: bool = true;
}

impl Board {
  pub fn legal_moves_for<const US: Color, GT: GenType>(
    &self,
    moves: &mut MoveList,
  ) {
    if GT::TACTICALS {
      super::gen_tacticals_for::<US>(self, moves);
    }

    if GT::QUIETS {
      super::gen_quiets_for::<US>(self, moves);
    }
  }

  pub fn collect_legal_moves<GT: GenType>(&self, moves: &mut MoveList) {
    if self.current.is_white() {
      self.legal_moves_for::<{ Color::White }, GT>(moves);
    } else {
      self.legal_moves_for::<{ Color::Black }, GT>(moves);
    }
  }

  /// Find all the legal moves for the current board state
  pub fn legal_moves<GT: GenType>(&self) -> MoveList {
    let mut moves = MoveList::new();

    self.collect_legal_moves::<GT>(&mut moves);

    moves
  }

  // Find a legal move corresponding to an un-annotated bare move, if any.
  pub fn find_move(&self, bare: BareMove) -> Option<Move> {
    let legals = self.legal_moves::<All>();
    legals.into_iter().find(|legal| legal.eq(&bare))
  }

  /// Check whether a move is legal to play in the current board position.
  ///
  /// This aims to be a lot cheaper than simply generating all the legal moves
  /// and checking whether the provided move is among them.
  ///
  /// This assumes the moves were generated by some kind of legal movegen.
  /// For example, we assume that promotions and castling happen on the
  /// 1st/8th ranks.
  pub fn is_legal(&self, mv: Move) -> bool {
    use PieceType::*;
    let us = self.current;
    let checkers = self.get_checkers();
    let num_checkers = checkers.count();
    let blockers = self.all_occupied();
    let src = mv.src();
    let tgt = mv.tgt();
    let capture_sq = mv.get_capture_sq();
    let captured = self.get_at(capture_sq);
    let king = self.kings(us).first();

    // There is a piece on the starting square
    let Some(piece) = self.get_at(src) else {
      return false;
    };

    // The piece is the correct color
    if piece.color() != us {
      return false;
    }

    // Make sure the move is pseudo-legal.
    let attacked = match piece.piece_type() {
      Pawn if mv.is_capture() => pawn_attacks(src, us),
      Pawn => pawn_squares(src, us, blockers),
      Knight => knight_squares(src),
      Bishop => bishop_squares(src, blockers),
      Rook => rook_squares(src, blockers),
      Queen => queen_squares(src, blockers),
      King => king_squares(src),
    };

    if !mv.is_castle() && !mv.is_en_passant() && !attacked.contains(tgt) {
      return false;
    }

    ////////////////////////////////////////////////////////////////////////
    //
    // Capture checks
    //
    ////////////////////////////////////////////////////////////////////////
    if let Some(captured) = captured {
      if !mv.is_capture() || captured.color() == us {
        return false;
      }
    }

    ////////////////////////////////////////////////////////////////////////
    //
    // Promotion checks
    //
    ////////////////////////////////////////////////////////////////////////
    if !piece.is_pawn()
      && (mv.is_promotion() || mv.is_en_passant() || mv.is_double_push())
    {
      return false;
    }

    if piece.is_pawn() && tgt.on_promo_rank(self.current) && !mv.is_promotion()
    {
      return false;
    }

    ////////////////////////////////////////////////////////////////////////
    //
    // En-passant checks
    //
    ////////////////////////////////////////////////////////////////////////

    if mv.is_en_passant() {
      let Some(ep_sq) = self.en_passant else {
        return false;
      };

      if ep_sq != tgt
        || !attacked.contains(ep_sq)
        || !captured.is_some_and(|p| p.is_pawn())
      {
        return false;
      }

      // Revealed checks
      let blockers = blockers
        ^ Bitboard::from(src)
        ^ Bitboard::from(tgt)
        ^ Bitboard::from(capture_sq);

      let hv_checkers = rook_squares(king, blockers) & self.hv_sliders(!us);
      let diag_checkers =
        bishop_squares(king, blockers) & self.diag_sliders(!us);

      if !hv_checkers.is_empty() || !diag_checkers.is_empty() {
        return false;
      }
    }

    ////////////////////////////////////////////////////////////////////////
    //
    // Double push checks
    //
    ////////////////////////////////////////////////////////////////////////

    // A pawn move of 2 squares must be flagged as a double push
    if !mv.is_double_push() && piece.is_pawn() && src.max_dist(tgt) == 2 {
      return false;
    }

    ////////////////////////////////////////////////////////////////////////
    //
    // Castling checks
    //
    ////////////////////////////////////////////////////////////////////////

    if mv.is_castle() {
      // The move is a valid castle move
      let ctype = CastleType::from_move(mv);

      // Castle must move the king
      // Castle must be legal
      if !piece.is_king() || !self.legal_castles().contains(&ctype) {
        return false;
      }
    }

    ////////////////////////////////////////////////////////////////////////
    //
    // King/legality checks
    //
    ////////////////////////////////////////////////////////////////////////

    // King can't move into check
    if piece.is_king() {
      let blockers = blockers & !self.kings(us);
      return !self.threats.contains(tgt)
        && (bishop_squares(tgt, blockers) & self.diag_sliders(!us)).is_empty()
        && (rook_squares(tgt, blockers) & self.hv_sliders(!us)).is_empty();
    }

    // If piece is pinned, make sure target square is inside pinray
    let pinrays = self.get_pinrays(us);

    if pinrays.contains(src) && !(pinrays & rays(king, src)).contains(tgt) {
      return false;
    }

    // Only king moves allowed when double checked
    if num_checkers > 1 {
      return false;
    }

    if num_checkers == 0 {
      return true;
    }

    // If in check, and we're not the king, we need to either
    // 1. Capture the checker
    // 2. Block the check
    let checker = checkers.first();
    return capture_sq == checker || between(checker, king).contains(tgt);
  }
}

////////////////////////////////////////////////////////////////////////////////
//
// Tests
//
////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
mod tests {
  use super::*;
  use crate::square::Square;
  use Square::*;

  #[test]
  fn double_pushes() {
    let board: Board =
      "rnbqkbnr/ppp1pppp/3p4/8/8/3P4/PPP1PPPP/RNBQKBNR w KQkq - 0 2"
        .parse()
        .unwrap();
    let legal_moves = board.legal_moves::<All>();

    // e2 can double-push
    assert!(
      legal_moves
        .iter()
        .find(|mv| mv.src() == Square::E2
          && mv.tgt() == Square::E4
          && mv.is_double_push())
        .is_some()
    );

    // d3 can't double-push
    assert!(
      legal_moves
        .iter()
        .find(|mv| mv.src() == Square::D3 && mv.tgt() == Square::D5)
        .is_none()
    );
  }

  #[test]
  fn pieces_must_block_to_counter_checks() {
    let board: Board = "1k6/8/8/5q2/8/8/4R3/1K6 w - - 0 1".parse().unwrap();
    let legal_moves = board.legal_moves::<All>();

    let rook_moves: Vec<Move> = legal_moves
      .into_iter()
      .filter(|mv| mv.src() == Square::E2)
      .collect();

    // Only two legal moves: block on c2 or e4
    assert_eq!(rook_moves.len(), 2);
    assert!(
      rook_moves
        .iter()
        .find(|mv| mv.tgt() == Square::C2)
        .is_some()
    );
    assert!(
      rook_moves
        .iter()
        .find(|mv| mv.tgt() == Square::E4)
        .is_some()
    )
  }

  #[test]
  fn king_must_move_out_of_check() {
    let board: Board = "1k6/8/8/5q2/8/3K4/8/8 w - - 0 1".parse().unwrap();
    let king_moves: Vec<Move> = board
      .legal_moves::<All>()
      .into_iter()
      .filter(|mv| mv.src() == Square::D3)
      .collect();

    // Only king moves are getting out of check
    assert_eq!(king_moves.len(), 6);
    assert!(
      king_moves
        .iter()
        .find(|mv| mv.tgt() == Square::E4)
        .is_none()
    );
    assert!(
      king_moves
        .iter()
        .find(|mv| mv.tgt() == Square::C2)
        .is_none()
    );
  }

  #[test]
  fn check_blocks_and_king_moves_combined() {
    let board: Board = "1k6/8/8/5q2/8/4P3/PP5r/RK6 w - - 0 1".parse().unwrap();
    let legal_moves = board.legal_moves::<All>();
    let king_moves: Vec<&Move> = legal_moves
      .iter()
      .filter(|mv| mv.src() == Square::B1)
      .collect();

    let pawn_moves: Vec<&Move> = legal_moves
      .iter()
      .filter(|mv| mv.src() == Square::E3)
      .collect();

    // Only legal moves are Kc1 and e4
    assert_eq!(legal_moves.len(), 2);

    // King's only move is c1
    assert_eq!(king_moves.len(), 1);
    assert_eq!(king_moves.first().unwrap().tgt(), Square::C1);

    // Pawn's only move is e4
    assert_eq!(pawn_moves.len(), 1);
    assert_eq!(pawn_moves.first().unwrap().tgt(), Square::E4);
  }

  #[test]
  fn pins() {
    let board: Board = "1k6/2q5/8/1n6/5B2/1R6/8/1K6 b - - 0 1".parse().unwrap();
    let legal_moves = board.legal_moves::<All>();

    let knight_moves: Vec<&Move> =
      legal_moves.iter().filter(|mv| mv.src() == B5).collect();

    let queen_moves: Vec<&Move> =
      legal_moves.iter().filter(|mv| mv.src() == C7).collect();

    // Knight is completely pinned
    assert_eq!(knight_moves.len(), 0);

    // Queen can move within the pin ray
    assert_eq!(queen_moves.len(), 3);
  }

  #[test]
  fn en_passant() {
    let board: Board = "1k6/8/8/8/3Pp3/8/8/1K6 b - d3 0 1".parse().unwrap();
    let legal_moves = board.legal_moves::<All>();

    let pawn_moves: Vec<&Move> =
      legal_moves.iter().filter(|mv| mv.src() == E4).collect();

    assert_eq!(
      pawn_moves.len(),
      2,
      "there are two legal pawn moves from e4"
    );

    let en_passant = pawn_moves.iter().find(|mv| mv.tgt() == D3);
    assert!(en_passant.is_some(), "We can capture en-passant");
    assert!(
      en_passant.unwrap().is_en_passant(),
      "The en-passant flag is set"
    );
  }

  #[test]
  fn en_passant_revealed_check() {
    let board: Board = "8/8/8/8/k2Pp2R/8/8/K7 b - d3 0 1".parse().unwrap();
    let legal_moves = board.legal_moves::<All>();

    let pawn_moves: Vec<&Move> =
      legal_moves.iter().filter(|mv| mv.src() == E4).collect();

    let en_passant = pawn_moves.iter().find(|mv| mv.tgt() == D3);
    assert!(
      en_passant.is_none(),
      "En-passant not allowed if it reveals a check"
    );
  }
}
