name: Run perft benchmark

on:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_perft:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo run -p simbelmyne --release -- perft --all --depth 5
